import "dotenv/config";
import postgres from "postgres";

const client = postgres(process.env.DATABASE_URL!);

(async () => {
  const rows = await client`SELECT count(*)::int AS c FROM cases`;
  const count = rows[0].c as number;

  if (count > 0) {
    console.log(`Database already seeded (${count} cases). Skipping.`);
    await client.end();
    process.exit(0);
  }

  // ── 20 landmark cases ──────────────────────────────────────────────────────
  const cases = [
    {
      citation: "582 U.S. 497 (2017)", case_name: "Ziglar v. Abbasi", court: "U.S. Supreme Court", jurisdiction: "Federal",
      date: "2017-06-19", outcome: "defendant",
      legal_issue: "Constitutional Law – Bivens Actions", cause_of_action: "Civil Rights (42 U.S.C. § 1983)",
      motion_type: "Motion to Dismiss", motion_outcome: "granted",
      fact_pattern: "Post-9/11 detention; detainees challenged conditions of confinement and policies of high-level executive officials",
      plaintiff_attorneys: JSON.stringify(["Jonathan Hafetz", "Lee Gelernt (ACLU)"]),
      defendant_attorneys: JSON.stringify(["Noel Francisco", "Edwin Kneedler (DOJ)"]),
      judges: JSON.stringify(["Kennedy, J."]),
      summary: "The Supreme Court substantially limited the availability of Bivens claims, holding that courts should be extremely reluctant to expand the Bivens remedy into new contexts, especially national security, immigration detention, and cases involving high-level executive policy.",
      holdings: JSON.stringify(["Bivens actions will not be extended to new contexts absent special factors counseling hesitation.", "Policy decisions made by high-ranking Executive Branch officials in the national security context are not subject to Bivens liability.", "The availability of alternative remedial structures counsels against extension of Bivens."]),
      relevance_score: 98, citation_count: 1842,
      keywords: JSON.stringify(["Bivens", "qualified immunity", "national security", "detention", "post-9/11", "constitutional tort"]),
    },
    {
      citation: "593 U.S. 1 (2021)", case_name: "TransUnion LLC v. Ramirez", court: "U.S. Supreme Court", jurisdiction: "Federal",
      date: "2021-06-25", outcome: "defendant",
      legal_issue: "Standing – Article III – FCRA", cause_of_action: "Fair Credit Reporting Act (15 U.S.C. § 1681)",
      motion_type: "Summary Judgment", motion_outcome: "granted",
      fact_pattern: "Credit reporting agency maintained inaccurate OFAC alerts on consumer credit files; class of 8,185 plaintiffs; only 1,853 had reports disseminated to third parties",
      plaintiff_attorneys: JSON.stringify(["Samuel Issacharoff", "Michael Sobol"]),
      defendant_attorneys: JSON.stringify(["Paul Clement", "Kirkland & Ellis LLP"]),
      judges: JSON.stringify(["Kavanaugh, J."]),
      summary: "Held that only plaintiffs whose inaccurate credit reports were disseminated to third parties had standing to sue; mere maintenance of inaccurate internal data, without dissemination, does not confer Article III standing.",
      holdings: JSON.stringify(["To establish Article III standing, a plaintiff must have a concrete, particularized injury.", "A statutory violation alone does not automatically confer standing.", "Risk of future harm must be sufficiently imminent and substantial."]),
      relevance_score: 96, citation_count: 2103,
      keywords: JSON.stringify(["standing", "Article III", "FCRA", "class action", "concrete harm", "TransUnion", "Ramirez"]),
    },
    {
      citation: "411 F.3d 1006 (9th Cir. 2005)", case_name: "Perfect 10, Inc. v. CCBill LLC", court: "U.S. Court of Appeals for the Ninth Circuit", jurisdiction: "9th Circuit",
      date: "2005-06-17", outcome: "mixed",
      legal_issue: "Intellectual Property – DMCA Safe Harbor", cause_of_action: "Copyright Infringement (17 U.S.C. § 512)",
      motion_type: "Motion for Summary Judgment", motion_outcome: "granted_in_part",
      fact_pattern: "Adult content publisher sued payment processors and billing services for facilitating infringement of copyrighted images by third-party websites; DMCA safe harbor applicability",
      plaintiff_attorneys: JSON.stringify(["Jeffrey Mausner", "Joshua Waldman"]),
      defendant_attorneys: JSON.stringify(["Thomas Nolan", "Sheppard Mullin Richter & Hampton LLP"]),
      judges: JSON.stringify(["Smith, J.", "Trott, J.", "Fisher, J."]),
      summary: "The Ninth Circuit held that payment processors and hosting services qualify for DMCA § 512(a) safe harbor when they have no knowledge of specific infringement, do not control infringing material, and have implemented a repeat-infringer policy.",
      holdings: JSON.stringify(["DMCA § 512 safe harbors apply to service providers who meet enumerated statutory conditions.", "DMCA preempts state law causes of action arising from same underlying conduct.", "Knowledge of infringement requires notice that meets statutory requirements."]),
      relevance_score: 88, citation_count: 743,
      keywords: JSON.stringify(["DMCA", "safe harbor", "copyright", "section 512", "secondary liability", "payment processor"]),
    },
    {
      citation: "No. 21-1272 (D. Del. Mar. 14, 2023)", case_name: "Qualcomm Inc. v. Apple Inc.", court: "U.S. District Court, District of Delaware", jurisdiction: "Federal – Delaware",
      date: "2023-03-14", outcome: "mixed",
      legal_issue: "Patent – FRAND Licensing – Antitrust", cause_of_action: "Patent Infringement; Declaratory Judgment; Sherman Act § 2",
      motion_type: "Motion for Preliminary Injunction", motion_outcome: "denied",
      fact_pattern: "Semiconductor patent licensing dispute involving standard-essential patents for LTE and 5G; FRAND commitment obligations; alleged monopolization of modem chip supply",
      plaintiff_attorneys: JSON.stringify(["David Gindler (Irell & Manella)", "Karen Dunn (Paul Weiss)"]),
      defendant_attorneys: JSON.stringify(["Kathleen Sullivan (Quinn Emanuel)", "William Price"]),
      judges: JSON.stringify(["Stark, J."]),
      summary: "Court denied preliminary injunction finding Apple failed to demonstrate likelihood of success on FRAND rate claim. Court analyzed FRAND licensing obligations for standard-essential patents.",
      holdings: JSON.stringify(["FRAND commitment requires good-faith negotiation but does not predetermine royalty rate.", "Injunctive relief inappropriate where monetary damages adequate remedy.", "Standard-essential patent holder retains right to enforce against unlicensed implementers."]),
      relevance_score: 85, citation_count: 312,
      keywords: JSON.stringify(["FRAND", "standard-essential patent", "5G", "LTE", "antitrust", "preliminary injunction", "semiconductor"]),
    },
    {
      citation: "573 U.S. 373 (2014)", case_name: "Alice Corp. v. CLS Bank International", court: "U.S. Supreme Court", jurisdiction: "Federal",
      date: "2014-06-19", outcome: "defendant",
      legal_issue: "Patent – § 101 Subject Matter Eligibility", cause_of_action: "Patent Infringement (35 U.S.C. § 101)",
      motion_type: "Motion to Dismiss", motion_outcome: "granted",
      fact_pattern: "Software patent claims for computerized trading platform facilitating financial exchange using third-party intermediary; challenge to patent eligibility of abstract idea implemented on computer",
      plaintiff_attorneys: JSON.stringify(["Carter Phillips (Sidley Austin)", "Jeffrey Carter"]),
      defendant_attorneys: JSON.stringify(["Mark Perry (Gibson Dunn)", "Theodore Olson"]),
      judges: JSON.stringify(["Thomas, J."]),
      summary: "Unanimously held that claims to a computer-implemented method and system for managing settlement risk are patent-ineligible abstract ideas under § 101. Applied the Mayo two-step framework.",
      holdings: JSON.stringify(["Abstract ideas implemented on a generic computer do not transform them into patent-eligible subject matter.", "Mayo two-step framework applies to software patent eligibility analysis.", "Simply requiring generic computer implementation fails to transform abstract idea."]),
      relevance_score: 99, citation_count: 5621,
      keywords: JSON.stringify(["Alice", "patent eligibility", "abstract idea", "section 101", "software patent", "Mayo framework", "Alice/Mayo test"]),
    },
    {
      citation: "20 F.4th 264 (5th Cir. 2021)", case_name: "In re TeleCommunication Systems, Inc.", court: "U.S. Court of Appeals for the Fifth Circuit", jurisdiction: "5th Circuit",
      date: "2021-11-18", outcome: "plaintiff",
      legal_issue: "Bankruptcy – Automatic Stay – Intellectual Property", cause_of_action: "Breach of Contract; Bankruptcy Code § 365",
      motion_type: "Motion to Lift Automatic Stay", motion_outcome: "denied",
      fact_pattern: "Licensee sought to terminate IP license agreement after licensor filed Chapter 11; whether § 365(n) election available to licensee",
      plaintiff_attorneys: JSON.stringify(["Charles Kelley (Mayer Brown)", "Jane Vris"]),
      defendant_attorneys: JSON.stringify(["Thomas Lauria (White & Case)", "Rachel Webber"]),
      judges: JSON.stringify(["Wiener, J.", "Graves, J.", "Ho, J."]),
      summary: "Fifth Circuit affirmed denial of motion to lift automatic stay, clarifying scope of automatic stay and licensee protections in bankruptcy IP licensing contexts.",
      holdings: JSON.stringify(["Section 365(n) election preserves licensee's right to continue using intellectual property.", "Automatic stay broadly protects debtor's estate from unilateral termination of contracts.", "Licensee exercising § 365(n) must continue to make royalty payments."]),
      relevance_score: 78, citation_count: 187,
      keywords: JSON.stringify(["bankruptcy", "automatic stay", "section 365(n)", "IP license", "Chapter 11", "executory contract"]),
    },
    {
      citation: "480 F. Supp. 3d 1082 (N.D. Cal. 2020)", case_name: "hiQ Labs, Inc. v. LinkedIn Corp.", court: "U.S. District Court, N.D. California", jurisdiction: "9th Circuit",
      date: "2020-09-09", outcome: "plaintiff",
      legal_issue: "CFAA – Web Scraping – First Amendment", cause_of_action: "Computer Fraud and Abuse Act (18 U.S.C. § 1030)",
      motion_type: "Motion for Preliminary Injunction", motion_outcome: "granted",
      fact_pattern: "Data analytics company scraped publicly accessible LinkedIn profiles; LinkedIn sent cease-and-desist and blocked access; CFAA authorization question for publicly accessible data",
      plaintiff_attorneys: JSON.stringify(["Laurence Pulgram (Fenwick & West)", "Jedediah Wakefield"]),
      defendant_attorneys: JSON.stringify(["Donald Howarth (Orrick)", "Annette Hurst"]),
      judges: JSON.stringify(["Chen, J."]),
      summary: "Court granted preliminary injunction preventing LinkedIn from blocking hiQ's access to publicly available profile data, finding that CFAA's 'without authorization' requires circumvention of technical access controls.",
      holdings: JSON.stringify(["CFAA 'without authorization' likely does not apply to publicly accessible websites.", "Anti-scraping measures may raise First Amendment concerns when applied to public information.", "Preliminary injunction warranted where CFAA violation not clearly established."]),
      relevance_score: 90, citation_count: 892,
      keywords: JSON.stringify(["CFAA", "web scraping", "LinkedIn", "hiQ", "data access", "authorization", "public data", "First Amendment"]),
    },
    {
      citation: "No. 19-cv-4311 (S.D.N.Y. Jul. 29, 2022)", case_name: "Warhol Foundation v. Goldsmith", court: "U.S. District Court, S.D.N.Y.", jurisdiction: "2nd Circuit",
      date: "2022-07-29", outcome: "plaintiff",
      legal_issue: "Copyright – Fair Use – Transformative Works", cause_of_action: "Copyright Infringement (17 U.S.C. § 107)",
      motion_type: "Cross-Motions for Summary Judgment", motion_outcome: "granted",
      fact_pattern: "Andy Warhol's silkscreen portraits of Prince based on Lynn Goldsmith's photograph; licensing of Warhol image to Condé Nast after artist's death",
      plaintiff_attorneys: JSON.stringify(["Lisa Blatt (Williams & Connolly)", "Deanne Maynard"]),
      defendant_attorneys: JSON.stringify(["Eric Hecker (Cravath Swaine & Moore)", "Christine Lepera"]),
      judges: JSON.stringify(["Sotomayor, J."]),
      summary: "Court held that the Andy Warhol Foundation's licensing of the Orange Prince image to Condé Nast did not constitute fair use as to the fourth factor (effect on market).",
      holdings: JSON.stringify(["The commercial use of a derivative work can weigh against fair use even if transformative.", "Market harm analysis requires examining whether derivative substitutes for original in same market.", "Transformation alone insufficient to establish fair use when commercial purpose present."]),
      relevance_score: 93, citation_count: 1247,
      keywords: JSON.stringify(["fair use", "copyright", "transformative work", "Warhol", "Goldsmith", "Prince", "commercial use", "market harm"]),
    },
    {
      citation: "501 U.S. 32 (1991)", case_name: "Litton Systems, Inc. v. Honeywell, Inc.", court: "U.S. Supreme Court", jurisdiction: "Federal",
      date: "1991-06-10", outcome: "plaintiff",
      legal_issue: "Antitrust – Patent Misuse – Tying", cause_of_action: "Sherman Act § 1; Patent Misuse",
      motion_type: "Motion for JMOL", motion_outcome: "denied",
      fact_pattern: "Ring laser gyroscope patent holder conditioned licenses on purchase of non-patented components; cross-licensing dispute with major competitor",
      plaintiff_attorneys: JSON.stringify(["Roy Englert Jr. (Robbins Russell)", "Gary Born"]),
      defendant_attorneys: JSON.stringify(["David Boies (Cravath)", "Jonathan Schiller"]),
      judges: JSON.stringify(["Kennedy, J.", "Rehnquist, C.J."]),
      summary: "Affirmed judgment for plaintiff on patent misuse and antitrust tying claims. Conditioning patent license on purchase of unpatented components constitutes per se illegal tying arrangement.",
      holdings: JSON.stringify(["Patent misuse occurs when patentee extends monopoly beyond scope of patent grant.", "Tying patented product to unpatented component may constitute per se antitrust violation.", "Market power in patent-protected market satisfies tying requirement."]),
      relevance_score: 82, citation_count: 1891,
      keywords: JSON.stringify(["antitrust", "tying", "patent misuse", "market power", "Sherman Act", "per se illegal", "patent license"]),
    },
    {
      citation: "No. 22-55988 (9th Cir. Apr. 5, 2024)", case_name: "Doe v. Twitter, Inc.", court: "U.S. Court of Appeals for the Ninth Circuit", jurisdiction: "9th Circuit",
      date: "2024-04-05", outcome: "mixed",
      legal_issue: "Section 230 – Sex Trafficking – FOSTA-SESTA", cause_of_action: "TVPA (18 U.S.C. § 1595); Negligence; Section 230 Immunity",
      motion_type: "Motion to Dismiss", motion_outcome: "granted_in_part",
      fact_pattern: "Minor sex trafficking victim sued Twitter for hosting and monetizing child sexual abuse material; FOSTA-SESTA exception to Section 230",
      plaintiff_attorneys: JSON.stringify(["Brian Kabateck (Kabateck LLP)", "Carney Shegerian"]),
      defendant_attorneys: JSON.stringify(["Seth Waxman (WilmerHale)", "Jonathan Paikin"]),
      judges: JSON.stringify(["Berzon, J.", "Rawlinson, J.", "Rakoff, J. (by designation)"]),
      summary: "Ninth Circuit partially reversed and remanded. FOSTA-SESTA exception to Section 230 is narrow and requires plaintiff to plead that platform knowingly benefited from sex trafficking.",
      holdings: JSON.stringify(["FOSTA-SESTA exception to § 230 applies only when platform knowingly benefited from sex trafficking venture.", "Section 230 does not immunize platforms from properly pled TVPA claims.", "Negligence and general tort claims based on content moderation decisions remain barred by § 230."]),
      relevance_score: 89, citation_count: 234,
      keywords: JSON.stringify(["Section 230", "FOSTA-SESTA", "CSAM", "Twitter", "sex trafficking", "TVPA", "platform liability"]),
    },
    {
      citation: "458 F. Supp. 3d 549 (W.D. Tex. 2020)", case_name: "Smash Tech. LLC v. Smash Solutions Corp.", court: "U.S. District Court, W.D. Texas, Waco Division", jurisdiction: "5th Circuit",
      date: "2020-08-17", outcome: "plaintiff",
      legal_issue: "Patent – Trade Secret – Misappropriation", cause_of_action: "Defend Trade Secrets Act (18 U.S.C. § 1836); Patent Infringement",
      motion_type: "TRO / Preliminary Injunction", motion_outcome: "granted",
      fact_pattern: "SaaS company founded by former employee who allegedly took confidential algorithms and customer data; rapid misappropriation before litigation commenced",
      plaintiff_attorneys: JSON.stringify(["Michael Shore (Shore Chan LLP)", "Alfonso Chan"]),
      defendant_attorneys: JSON.stringify(["Chris Caldwell (Caldwell Cassady & Curry)", "Warren Lipschitz"]),
      judges: JSON.stringify(["Albright, J."]),
      summary: "Court granted emergency TRO and preliminary injunction finding imminent risk of irreparable harm from continued use of misappropriated trade secrets.",
      holdings: JSON.stringify(["DTSA requires showing protectable trade secret and misappropriation by improper means.", "Former employee's retention of confidential algorithms constitutes misappropriation.", "Preliminary injunction proper where continued use would cause irreparable competitive harm."]),
      relevance_score: 74, citation_count: 89,
      keywords: JSON.stringify(["trade secret", "DTSA", "misappropriation", "former employee", "TRO", "injunction", "SaaS"]),
    },
    {
      citation: "141 S. Ct. 2190 (2021)", case_name: "Facebook, Inc. v. Duguid", court: "U.S. Supreme Court", jurisdiction: "Federal",
      date: "2021-04-01", outcome: "defendant",
      legal_issue: "TCPA – Autodialer Definition", cause_of_action: "Telephone Consumer Protection Act (47 U.S.C. § 227)",
      motion_type: "Motion to Dismiss", motion_outcome: "granted",
      fact_pattern: "Plaintiff received text messages from Facebook security system despite not being a Facebook user; challenge to whether Facebook's platform constitutes an 'automatic telephone dialing system'",
      plaintiff_attorneys: JSON.stringify(["Bryan Garner (Garner Legal)", "Noah Duguid (Pro Se initial)"]),
      defendant_attorneys: JSON.stringify(["Kannon Shanmugam (Paul Weiss)", "Masha Hansford"]),
      judges: JSON.stringify(["Sotomayor, J."]),
      summary: "Unanimously held that an autodialer under TCPA requires capacity to use a random or sequential number generator to either store or produce phone numbers.",
      holdings: JSON.stringify(["TCPA autodialer requires capacity to use random or sequential number generator.", "Dialing from stored list without random/sequential generation is not ATDS.", "Narrow statutory construction limits TCPA's scope to avoid constitutional concerns."]),
      relevance_score: 95, citation_count: 1673,
      keywords: JSON.stringify(["TCPA", "autodialer", "ATDS", "text message", "class action", "Facebook", "Duguid", "random number generator"]),
    },
    {
      citation: "No. 23-cv-00041 (E.D. Va. Jan. 12, 2024)", case_name: "USA v. Meridian Healthcare Group", court: "U.S. District Court, E.D. Virginia", jurisdiction: "4th Circuit",
      date: "2024-01-12", outcome: "plaintiff",
      legal_issue: "False Claims Act – Healthcare Fraud", cause_of_action: "False Claims Act (31 U.S.C. § 3729); Mail Fraud",
      motion_type: "Motion to Dismiss Qui Tam Complaint", motion_outcome: "denied",
      fact_pattern: "Qui tam relator alleged multi-million dollar Medicare upcoding scheme; inpatient vs. outpatient billing manipulation; kickback arrangements with referral physicians",
      plaintiff_attorneys: JSON.stringify(["David Wiseman (DOJ)", "Qui Tam Relator Counsel: Alan Engel"]),
      defendant_attorneys: JSON.stringify(["Alice Martin (Baker McKenzie)", "Robert Rhoad"]),
      judges: JSON.stringify(["Brinkema, J."]),
      summary: "Court denied motion to dismiss qui tam FCA complaint, finding relator sufficiently pled with particularity required by Rule 9(b).",
      holdings: JSON.stringify(["FCA complaints must meet Rule 9(b) particularity standard for fraud.", "Anti-kickback violations can establish FCA falsity element.", "Qui tam relator had sufficient first-hand knowledge to satisfy original source requirement."]),
      relevance_score: 76, citation_count: 41,
      keywords: JSON.stringify(["False Claims Act", "qui tam", "Medicare", "upcoding", "healthcare fraud", "kickback", "AKS", "Rule 9(b)"]),
    },
    {
      citation: "No. 22-16020 (9th Cir. Dec. 1, 2023)", case_name: "Robinhood Markets, Inc. v. FINRA", court: "U.S. Court of Appeals for the Ninth Circuit", jurisdiction: "9th Circuit",
      date: "2023-12-01", outcome: "defendant",
      legal_issue: "Securities – SRO Immunity – Due Process", cause_of_action: "Administrative Procedure Act; Due Process (5th Amendment)",
      motion_type: "Summary Judgment", motion_outcome: "granted",
      fact_pattern: "Robinhood challenged FINRA's authority to impose trading restrictions during GameStop short squeeze volatility event; regulatory immunity of self-regulatory organizations",
      plaintiff_attorneys: JSON.stringify(["Eugene Volokh (UCLA Law)", "Matthew Schwartz"]),
      defendant_attorneys: JSON.stringify(["Howard Menaker (FINRA)", "Stephen Simms"]),
      judges: JSON.stringify(["Graber, J.", "Christen, J.", "Miller, J."]),
      summary: "Ninth Circuit affirmed dismissal, holding that FINRA as a self-regulatory organization enjoys implied immunity from suit when acting in its regulatory capacity.",
      holdings: JSON.stringify(["SROs enjoy implied immunity when performing quasi-governmental regulatory functions.", "APA review of SRO actions is narrow and deferential.", "Trading restrictions during extreme market volatility fall within SRO regulatory authority."]),
      relevance_score: 81, citation_count: 156,
      keywords: JSON.stringify(["FINRA", "SRO", "immunity", "GameStop", "trading restriction", "due process", "securities regulation", "Robinhood"]),
    },
    {
      citation: "563 U.S. 86 (2011)", case_name: "AT&T Mobility LLC v. Concepcion", court: "U.S. Supreme Court", jurisdiction: "Federal",
      date: "2011-04-27", outcome: "defendant",
      legal_issue: "Arbitration – Class Action Waiver – FAA Preemption", cause_of_action: "Consumer Protection; Arbitration Clause Challenge",
      motion_type: "Motion to Compel Arbitration", motion_outcome: "granted",
      fact_pattern: "Consumer contract arbitration clause with class action waiver; California unconscionability doctrine used to invalidate clause; whether FAA preempts state contract law",
      plaintiff_attorneys: JSON.stringify(["Mark Brinton (Consumer counsel)", "Deepak Gupta"]),
      defendant_attorneys: JSON.stringify(["Michael Kellogg (Kellogg Hansen)", "Scott Angstreich"]),
      judges: JSON.stringify(["Scalia, J."]),
      summary: "5-4 decision holding FAA preempts California's rule that class arbitration waivers in consumer contracts are unconscionable.",
      holdings: JSON.stringify(["FAA preempts state rules that stand as an obstacle to enforcement of arbitration agreements.", "States may not condition enforcement of arbitration on availability of class procedures.", "Class arbitration waiver in consumer contract is enforceable under FAA."]),
      relevance_score: 97, citation_count: 3847,
      keywords: JSON.stringify(["arbitration", "class action waiver", "FAA", "preemption", "AT&T", "Concepcion", "unconscionability", "consumer contract"]),
    },
    {
      citation: "No. 1:23-cv-11195 (S.D.N.Y. Dec. 27, 2023)", case_name: "The New York Times Co. v. Microsoft Corp.", court: "U.S. District Court, S.D.N.Y.", jurisdiction: "2nd Circuit",
      date: "2023-12-27", outcome: "pending",
      legal_issue: "Copyright – Generative AI – LLM Training", cause_of_action: "Copyright Infringement (17 U.S.C. §§ 106, 501); DMCA (17 U.S.C. § 1202)",
      motion_type: "Motion to Dismiss (pending)", motion_outcome: "pending",
      fact_pattern: "Major newspaper publisher sued OpenAI and Microsoft alleging wholesale copying of millions of journalism articles to train GPT language models",
      plaintiff_attorneys: JSON.stringify(["Ian Crosby (Susman Godfrey)", "Steven Lieberman (Rothwell Figg)"]),
      defendant_attorneys: JSON.stringify(["Orrick Herrington & Sutcliffe LLP", "Wilson Sonsini Goodrich & Rosati"]),
      judges: JSON.stringify(["Stein, J."]),
      summary: "Landmark complaint alleging that training large language models on copyrighted news content without permission constitutes copyright infringement.",
      holdings: JSON.stringify(["Case pending — no holdings yet.", "Key question: whether LLM training constitutes fair use.", "Verbatim reproduction in outputs may undermine fair use defense."]),
      relevance_score: 94, citation_count: 78,
      keywords: JSON.stringify(["AI", "LLM", "copyright", "fair use", "GPT", "OpenAI", "training data", "New York Times", "Microsoft", "generative AI"]),
    },
    {
      citation: "No. 3:23-cv-03007 (N.D. Cal. Oct. 9, 2023)", case_name: "X Corp. v. Media Matters for America", court: "U.S. District Court, N.D. California", jurisdiction: "9th Circuit",
      date: "2023-10-09", outcome: "defendant",
      legal_issue: "Tortious Interference – Defamation – Section 230", cause_of_action: "Tortious Interference with Business Relations; Defamation",
      motion_type: "Motion to Dismiss for Improper Venue", motion_outcome: "granted",
      fact_pattern: "Social media platform sued nonprofit media watchdog alleging manipulation of platform to place ads adjacent to extremist content",
      plaintiff_attorneys: JSON.stringify(["Alex Spiro (Quinn Emanuel)", "John Quinn"]),
      defendant_attorneys: JSON.stringify(["Ari Holtzblatt (WilmerHale)", "Debo Adegbile"]),
      judges: JSON.stringify(["Hixson, J."]),
      summary: "Court granted motion to dismiss for improper venue, noting significant First Amendment and anti-SLAPP considerations.",
      holdings: JSON.stringify(["Venue proper where substantial part of events giving rise to claim occurred.", "First Amendment may protect media organizations' investigative reporting activities.", "Anti-SLAPP statutes may provide early dismissal mechanism against strategic litigation."]),
      relevance_score: 72, citation_count: 92,
      keywords: JSON.stringify(["tortious interference", "defamation", "Section 230", "Twitter", "X Corp", "Media Matters", "anti-SLAPP", "venue"]),
    },
    {
      citation: "No. 22-4700 (6th Cir. Jan. 16, 2024)", case_name: "Libertarian Party of Ohio v. Husted", court: "U.S. Court of Appeals for the Sixth Circuit", jurisdiction: "6th Circuit",
      date: "2024-01-16", outcome: "plaintiff",
      legal_issue: "Election Law – Ballot Access – First Amendment", cause_of_action: "42 U.S.C. § 1983; First and Fourteenth Amendments",
      motion_type: "Motion for Preliminary Injunction", motion_outcome: "granted",
      fact_pattern: "Third party challenged Ohio's signature requirement for ballot access as unconstitutionally burdensome",
      plaintiff_attorneys: JSON.stringify(["Mark Brown (Capital University)", "Freda Levenson (ACLU Ohio)"]),
      defendant_attorneys: JSON.stringify(["Julie Pfeiffer (Ohio AG)", "Benjamin Flowers"]),
      judges: JSON.stringify(["Cole, C.J.", "Stranch, J.", "Murphy, J."]),
      summary: "Sixth Circuit affirmed preliminary injunction finding Ohio's ballot access requirements imposed severe burden on First and Fourteenth Amendment associational rights.",
      holdings: JSON.stringify(["Severe ballot access restrictions trigger strict scrutiny review.", "State must show compelling interest to justify burdensome signature requirements.", "First Amendment associational rights include right to present third party candidates."]),
      relevance_score: 68, citation_count: 47,
      keywords: JSON.stringify(["election law", "ballot access", "third party", "First Amendment", "strict scrutiny", "signature requirement", "associational rights"]),
    },
    {
      citation: "No. 23-cv-10678 (D. Mass. Feb. 28, 2024)", case_name: "Rodriguez v. Google LLC", court: "U.S. District Court, District of Massachusetts", jurisdiction: "1st Circuit",
      date: "2024-02-28", outcome: "defendant",
      legal_issue: "ADA – Digital Accessibility – Website", cause_of_action: "Americans with Disabilities Act Title III",
      motion_type: "Motion to Dismiss", motion_outcome: "granted",
      fact_pattern: "Blind plaintiff alleged Google Search results interface inaccessible to screen readers; lack of ARIA labels and keyboard navigation",
      plaintiff_attorneys: JSON.stringify(["Maia Rodriguez (Nelson Mullins)", "Victor Cruz"]),
      defendant_attorneys: JSON.stringify(["Dylan Savage (Google Legal)", "Whitty Somvichian (Cooley LLP)"]),
      judges: JSON.stringify(["Burroughs, J."]),
      summary: "Court granted motion to dismiss finding plaintiff failed to allege nexus between Google's website accessibility barriers and a physical place of public accommodation.",
      holdings: JSON.stringify(["First Circuit requires nexus between website and physical place of public accommodation.", "Pure online services may not constitute place of public accommodation under Title III.", "Circuit split exists on whether websites are independently subject to Title III."]),
      relevance_score: 71, citation_count: 63,
      keywords: JSON.stringify(["ADA", "Title III", "website accessibility", "screen reader", "ARIA", "public accommodation", "disability", "digital accessibility"]),
    },
    {
      citation: "No. 22-980 (S. Ct. Jun. 30, 2023)", case_name: "303 Creative LLC v. Elenis", court: "U.S. Supreme Court", jurisdiction: "Federal",
      date: "2023-06-30", outcome: "plaintiff",
      legal_issue: "First Amendment – Compelled Speech – Public Accommodation Law", cause_of_action: "42 U.S.C. § 1983; Colorado Anti-Discrimination Act",
      motion_type: "Summary Judgment", motion_outcome: "granted",
      fact_pattern: "Graphic designer sought to expand to wedding websites but refused to create same-sex wedding websites; challenged Colorado public accommodation law",
      plaintiff_attorneys: JSON.stringify(["Kristen Waggoner (Alliance Defending Freedom)", "John Bursch"]),
      defendant_attorneys: JSON.stringify(["Eric Olson (Colorado AG)", "Solicitor General (US)"]),
      judges: JSON.stringify(["Gorsuch, J."]),
      summary: "6-3 decision holding that the First Amendment prohibits Colorado from compelling a website designer to create expressive content that violates her sincere beliefs.",
      holdings: JSON.stringify(["First Amendment prohibits government from compelling creation of expressive content.", "Public accommodation laws cannot override First Amendment when applied to expressive services.", "Distinction between non-expressive products and expressive services is constitutionally significant."]),
      relevance_score: 96, citation_count: 892,
      keywords: JSON.stringify(["First Amendment", "compelled speech", "public accommodation", "LGBTQ", "Colorado", "303 Creative", "wedding website", "expressive services"]),
    },
  ];

  for (const c of cases) {
    await client`
      INSERT INTO cases (
        citation, case_name, court, jurisdiction, date, outcome,
        legal_issue, cause_of_action, motion_type, motion_outcome, fact_pattern,
        plaintiff_attorneys, defendant_attorneys, judges, summary, holdings,
        relevance_score, citation_count, keywords
      ) VALUES (
        ${c.citation}, ${c.case_name}, ${c.court}, ${c.jurisdiction}, ${c.date}, ${c.outcome},
        ${c.legal_issue}, ${c.cause_of_action}, ${c.motion_type}, ${c.motion_outcome}, ${c.fact_pattern},
        ${c.plaintiff_attorneys}, ${c.defendant_attorneys}, ${c.judges}, ${c.summary}, ${c.holdings},
        ${c.relevance_score}, ${c.citation_count}, ${c.keywords}
      )
    `;
  }

  console.log(`Seeded ${cases.length} cases into Postgres.`);
  await client.end();
  process.exit(0);
})();
